/**
 * DB Initialization Script
 * The Common password is : "passmyclass"
 */
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ENABLED, LAST_MODIFIED)
VALUES (1, 'staff', '$2a$10$.M2kuE5yBJr8.PXU.FaFyui1f.tsYYQqmWc07P1ZdEEoeEdU1hdhm', 'staff', 'staff', 'staff@staff.com', 1, PARSEDATETIME('01-09-2018', 'dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, ENABLED, LAST_MODIFIED)
VALUES (2, 'guest', '$2a$10$.M2kuE5yBJr8.PXU.FaFyui1f.tsYYQqmWc07P1ZdEEoeEdU1hdhm', 'guest', 'guest', 'guest@guest.com', 1, PARSEDATETIME('01-09-2018','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, ROLE) VALUES (3, 'GUEST');
INSERT INTO AUTHORITY (ID, ROLE) VALUES (4, 'STAFF');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 3);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 4);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 3);

INSERT INTO ROOM (ID, BOOKED, ROOM_NUMBER, ROOM_TYPE, BOOKED_UNTIL, USER_ID)
VALUES (5, 0, '1A', 'SUITE', null, null);
INSERT INTO ROOM (ID, BOOKED, ROOM_NUMBER, ROOM_TYPE, BOOKED_UNTIL, USER_ID)
VALUES (6, 0, '2B', 'DOUBLE', null, null);